[[redirects]]
  from = "/ludurana"
  to = "/marca/ludurana"
  status = 301
 
[[redirects]]
  from = "/urban-art-queen-fashion"
  to = "/marca/urban-art-queen-fashion"
  status = 301

[[redirects]]
  from = "/trate"
  to = "/marca/trate"
  status = 301
 
[[redirects]]
  from = "/pink-color-cosmetics"
  to = "/marca/pink-color-cosmetics"
  status = 301

[[redirects]]
  from = "/derma-chem"
  to = "/marca/derma-chem"
  status = 301

[[redirects]]
  from = "/uni-makeup"
  to = "/marca/uni-makeup"
  status = 301

[[redirects]]
  from = "/mylife"
  to = "/marca/mylife"
  status = 301

[[redirects]]
  from = "/maika-beauty"
  to = "/marca/maika-beauty"
  status = 301

[[redirects]]
  from = "/gloxme"
  to = "/marca/gloxme"
  status = 301

[[redirects]]
  from = "/pramaquiar"
  to = "/marca/pramaquiar"
  status = 301
 
[[redirects]]
  from = "/jackie-design"
  to = "/marca/jackie-design"
  status = 301

[[redirects]]
  from = "/dapop-cosmeticos"
  to = "/marca/dapop-cosmeticos"
  status = 301

[[redirects]]
  from = "/miss-lary"
  to = "/marca/miss-lary"
  status = 301

[[redirects]]
  from = "/cisne"
  to = "/marca/cisne"
  status = 301

[[redirects]]
  from = "/new-show"
  to = "/marca/new-show"
  status = 301

[[redirects]]
  from = "/face-beautiful"
  to = "/marca/face-beautiful"
  status = 301

[[redirects]]
  from = "/sp-colors"
  to = "/marca/sp-colors"
  status = 301

[[redirects]]
  from = "/mahav"
  to = "/marca/mahav"
  status = 301

[[redirects]]
  from = "/tracta"
  to = "/marca/tracta"
  status = 301

[[redirects]]
  from = "/qualis"
  to = "/marca/qualis"
  status = 301

[[redirects]]
  from = "/aimee-cosmeticos"
  to = "/marca/aimee-cosmeticos"
  status = 301

[[redirects]]
  from = "/real-love"
  to = "/marca/real-love"
  status = 301

[[redirects]]
  from = "/city-girls"
  to = "/marca/city-girls"
  status = 301

[[redirects]]
  from = "/belle-angel"
  to = "/marca/belle-angel"
  status = 301

[[redirects]]
  from = "/cat-make"
  to = "/marca/cat-make"
  status = 301

[[redirects]]
  from = "/sabrina-sato"
  to = "/marca/sabrina-sato"
  status = 301

[[redirects]]
  from = "/luv-beauty"
  to = "/marca/luv-beauty"
  status = 301

[[redirects]]
  from = "/mia-make"
  to = "/marca/mia-make"
  status = 301

[[redirects]]
  from = "/mandala"
  to = "/marca/mandala"
  status = 301

[[redirects]]
  from = "/adversa"
  to = "/marca/adversa"
  status = 301

[[redirects]]
  from = "/vult"
  to = "/marca/vult"
  status = 301

[[redirects]]
  from = "/miss-frandy"
  to = "/marca/miss-frandy"
  status = 301

[[redirects]]
  from = "/corina"
  to = "/marca/corina"
  status = 301

[[redirects]]
  from = "/bella-femme"
  to = "/marca/bella-femme"
  status = 301

[[redirects]]
  from = "/macrilan"
  to = "/marca/macrilan"
  status = 301

[[redirects]]
  from = "/vivai"
  to = "/marca/vivai"
  status = 301

[[redirects]]
  from = "/hello-mini"
  to = "/marca/hello-mini"
  status = 301

[[redirects]]
  from = "/jasmyne"
  to = "/marca/jasmyne"
  status = 301

[[redirects]]
  from = "/dalla-makeup"
  to = "/marca/dalla-makeup"
  status = 301

[[redirects]]
  from = "/bitarra"
  to = "/marca/bitarra"
  status = 301

[[redirects]]
  from = "/luisance"
  to = "/marca/luisance"
  status = 301

[[redirects]]
  from = "/tango-tg"
  to = "/marca/tango-tg"
  status = 301

[[redirects]]
  from = "/fenzza"
  to = "/marca/fenzza"
  status = 301

[[redirects]]
  from = "/deisy-perozzo"
  to = "/marca/deisy-perozzo"
  status = 301

[[redirects]]
  from = "/any-color-cosmeticos"
  to = "/marca/any-color-cosmeticos"
  status = 301

[[redirects]]
  from = "/bella-luce"
  to = "/marca/bella-luce"
  status = 301

[[redirects]]
  from = "/meilys"
  to = "/marca/meilys"
  status = 301

[[redirects]]
  from = "/ruby-face"
  to = "/marca/ruby-face"
  status = 301

[[redirects]]
  from = "/fenzza"
  to = "/marca/fenzza"
  status = 301

[[redirects]]
  from = "/max-love"
  to = "/marca/max-love"
  status = 301

[[redirects]]
  from = "/new-face"
  to = "/marca/new-face"
  status = 301

[[redirects]]
  from = "/super-poderes"
  to = "/marca/super-poderes"
  status = 301

[[redirects]]
  from = "/ruby-rose"
  to = "/marca/ruby-rose"
  status = 301

[build]
  publish = "publish"
  functions = "functions-zip"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr?slug=:splat"
  status = 200

[[headers]]
  for = "/storefront.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/storefront.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/storefront.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/checkout.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/checkout.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/chunk.*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=60, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, s-maxage=600"
